#!/bin/sh
VCS_REF=$(git rev-parse --short HEAD)
VCS_VERSION=$(git describe --tags --contains --always)

docker buildx build \
  --pull
  --output=type=image
  --platform linux/arm64,linux/amd64 \
	--build-arg VCS_REF="$VCS_REF" \
	--build-arg VCS_VERSION="$VCS_VERSION" \
	-f "$DOCKERFILE_PATH" -t "$IMAGE_NAME" .
